#! /usr/bin/env lua

local host = io.popen("uname -s"):read("*l")

print("Host: " .. host)

local cmd

local build_for_linux =
   "g++ -Wall -Wextra -g -O0 -o handmade_hero code/win32_handmade.cpp"

if host == "Linux" then
   print("Building for linux.")
   cmd = build_for_linux
else
   print("This platform is not supported yet.")
   os.exit(1)
end

os.execute(cmd)
