#! /usr/bin/env lua

local host = io.popen("uname -s"):read("*l")

print("Host: " .. host)

local GLFW_DIR = "deps/glfw-3.4"

local build_for_linux = table.concat({
   "g++ -Wall -Wextra -g -O0 --std=c++17",
   "-I ./"..GLFW_DIR.."/include",
   "-o handmade_hero",
   "code/win32_handmade.cpp",
   GLFW_DIR.."/build/src/libglfw3.a",
   "-lGL -lm",
}, " ")

local cmd

if host == "Linux" then
   print("Building for linux.")
   cmd = build_for_linux
else
   print("This platform is not supported yet.")
   os.exit(1)
end

print("RUNNING: " .. cmd)
os.execute(cmd)
